from itertools import product

import pytest
from qiskit import ClassicalRegister, QuantumCircuit, QuantumRegister
from qiskit.quantum_info import Pauli
from qiskit.synthesis import synth_circuit_from_stabilizers
from qiskit_aer import AerSimulator

from src.steane import (
    Stabilizers,
    append_syndrome_measurement,
    measure_stabilizer,
    syndrome,
)


# helper function which returns the operator S1^a_1 S2^a_2...S6^a_6 when given (a_1, ..., a_6) for a_i in {0,1}
def stabilizer_product(exponents):
    # initialize the composite operator to the identity
    result = Pauli("IIIIIII")

    for exponent, stabilizer in zip(exponents, Stabilizers):
        # for each iterable (exponent, stabilizer), if an exponent is non-zero, then multiply the corresponding stabilizer from the iterable to the composite operator
        # since our operators commute, we dont really have to worry about the order in which .compose() multiplies the tensor product of Pauli matrices (i.e. stabilizer) to the composite operator
        if exponent:
            result = result.compose(stabilizer)

    return result


# tests to make sure that each distinct pair of stabilizer generators commutes
def test_stabilizers_commute():
    for i, s_i in enumerate(Stabilizers):
        for s_j in Stabilizers[i + 1 :]:
            assert s_i.commutes(s_j)


# this function tests to ensure that no non-trivial product of stabilizers gives the identity operator (i.e. that our stabilizers are independent over F_2)
def test_stabilizers_independent():
    identity = Pauli("IIIIIII")

    # loops through all non-zero tuples in F_2^6 and checks that the product of stabilizers corresponding to that tuple is not the identity operator in the 7-qubit Pauli group.
    # repeat is a keyword for the product function from itertools that tells the function to compute the Cartesian product of [0,1] with itself repeat = len(Stabilizers) = 6 times.
    for exponents in product([0, 1], repeat=len(Stabilizers)):
        if exponents != (0, 0, 0, 0, 0, 0):
            assert stabilizer_product(exponents) != identity


# this checks to make sure that no product of the stabilizer generators gives -I. This ensures that the subgroup generated by the elements in Stabilizers satisfies one of the
# few main conditions defining a stabilizer for a stabilizer code.
def test_minus_identity_not_in_stabilizer():
    minus_identity = Pauli("-IIIIIII")

    for exponents in product([0, 1], repeat=len(Stabilizers)):
        if exponents != (0, 0, 0, 0, 0, 0):
            assert stabilizer_product(exponents) != minus_identity


# this series of errors tests four simple cases to ensure that our syndrome function works properly
def test_identity_has_zero_syndrome():
    error = Pauli("IIIIIII")
    assert syndrome(error) == (0, 0, 0, 0, 0, 0)


def test_x0_syndrome():
    error = Pauli("IIIIIIX")
    assert syndrome(error) == (0, 0, 0, 1, 1, 1)


def test_y0_syndrome():
    error = Pauli("IIIIIIY")
    assert syndrome(error) == (1, 1, 1, 1, 1, 1)


def test_z0_syndrome():
    error = Pauli("IIIIIIZ")
    assert syndrome(error) == (1, 1, 1, 0, 0, 0)


def test_weight_one_errors_have_distinct_nonzero_syndromes():
    all_syndromes = []

    for i in range(7):
        x_error = Pauli("I" * (6 - i) + "X" + "I" * i)
        y_error = Pauli("I" * (6 - i) + "Y" + "I" * i)
        z_error = Pauli("I" * (6 - i) + "Z" + "I" * i)

        all_syndromes.append(syndrome(x_error))
        all_syndromes.append(syndrome(y_error))
        all_syndromes.append(syndrome(z_error))

    zero_syndrome = (0, 0, 0, 0, 0, 0)

    assert len(set(all_syndromes)) == len(all_syndromes)
    assert zero_syndrome not in all_syndromes


def test_measure_stabilizer_plus_one_eigenstate():
    data = QuantumRegister(7, "data")
    ancilla = QuantumRegister(1, "anc")
    syndrome_bit = ClassicalRegister(1, "syndrome")

    qc = QuantumCircuit(data, ancilla, syndrome_bit)

    for i in range(7):
        qc.h(data[i])

    measure_stabilizer(
        qc,
        data,
        ancilla,
        syndrome_bit,
        Stabilizers[0],
        0,
    )

    simulator = AerSimulator()
    result = simulator.run(qc, shots=100).result()
    counts = result.get_counts()

    assert counts == {"0": 100}


def test_measure_stabilizer_minus_one_eigenstate():
    data = QuantumRegister(7, "data")
    ancilla = QuantumRegister(1, "anc")
    syndrome_bit = ClassicalRegister(1, "syndrome")

    qc = QuantumCircuit(data, ancilla, syndrome_bit)

    for i in range(7):
        qc.h(data[i])

    qc.z(data[0])

    measure_stabilizer(
        qc,
        data,
        ancilla,
        syndrome_bit,
        Stabilizers[0],
        0,
    )

    simulator = AerSimulator()
    result = simulator.run(qc, shots=100).result()
    counts = result.get_counts()

    assert counts == {"1": 100}


def test_measure_z_stabilizer_plus_one_eigenstate():
    data = QuantumRegister(7, "data")
    ancilla = QuantumRegister(1, "anc")
    syndrome_bit = ClassicalRegister(1, "syndrome")

    qc = QuantumCircuit(data, ancilla, syndrome_bit)

    measure_stabilizer(
        qc,
        data,
        ancilla,
        syndrome_bit,
        Stabilizers[3],
        0,
    )

    simulator = AerSimulator()
    result = simulator.run(qc, shots=100).result()
    counts = result.get_counts()

    assert counts == {"0": 100}


def test_append_syndrome_measurement():
    data = QuantumRegister(7, "data")
    ancilla = QuantumRegister(6, "anc")
    syndrome_bits = ClassicalRegister(6, "syndrome")

    qc = QuantumCircuit(data, ancilla, syndrome_bits)

    append_syndrome_measurement(
        qc,
        data,
        ancilla,
        syndrome_bits,
    )

    assert qc.count_ops()["measure"] == 6


@pytest.mark.parametrize(
    "pauli_type, qubit_index",
    list(product(["X", "Y", "Z"], range(7))),
)
def test_weight_one_circuit_syndrome_matches_algebraic_syndrome(
    pauli_type,
    qubit_index,
):
    data = QuantumRegister(7, "data")
    ancilla = QuantumRegister(6, "anc")
    syndrome_bits = ClassicalRegister(6, "syndrome")

    qc = QuantumCircuit(data, ancilla, syndrome_bits)

    logical_zero_stabilizers = [stabilizer.to_label() for stabilizer in Stabilizers] + [
        "ZZZZZZZ"
    ]

    logical_zero_circuit = synth_circuit_from_stabilizers(logical_zero_stabilizers)

    qc.compose(
        logical_zero_circuit,
        qubits=data,
        inplace=True,
    )

    error = Pauli("I" * (6 - qubit_index) + pauli_type + "I" * qubit_index)

    if pauli_type == "X":
        qc.x(data[qubit_index])
    elif pauli_type == "Y":
        qc.y(data[qubit_index])
    elif pauli_type == "Z":
        qc.z(data[qubit_index])

    append_syndrome_measurement(
        qc,
        data,
        ancilla,
        syndrome_bits,
    )

    simulator = AerSimulator()
    result = simulator.run(qc, shots=100).result()
    counts = result.get_counts()

    # Verifies determinism explicitly for our idealized noiseless circuit
    assert len(counts) == 1

    bitstring = next(iter(counts))
    bitstring = bitstring[::-1]
    measured_syndrome = tuple(int(bit) for bit in bitstring)

    assert measured_syndrome == syndrome(error)
