from itertools import product

from qiskit.quantum_info import Pauli

from src.steane import Stabilizers


# helper function which returns the operator S1^a_1 S2^a_2...S6^a_6 when given (a_1, ..., a_6) for a_i in {0,1}
def stabilizer_product(exponents):
    # initialize the composite operator to the identity
    result = Pauli("IIIIIII")

    for exponent, stabilizer in zip(exponents, Stabilizers):
        # for each iterable (exponent, stabilizer), if an exponent is non-zero, then multiply the corresponding stabilizer from the iterable to the composite operator
        # since our operators commute, we dont really have to worry about the order in which .compose() multiplies the tensor product of Pauli matrices (i.e. stabilizer) to the composite operator
        if exponent:
            result = result.compose(stabilizer)

    return result


# tests to make sure that each distinct pair of stabilizer generators commutes
def test_stabilizers_commute():
    for i, s_i in enumerate(Stabilizers):
        for s_j in Stabilizers[i + 1 :]:
            assert s_i.commutes(s_j)


# this function tests to ensure that no non-trivial product of stabilizers gives the identity operator (i.e. that our stabilizers are independent over F_2)
def test_stabilizers_independent():
    identity = Pauli("IIIIIII")

    # loops through all non-zero tuples in F_2^6 and checks that the product of stabilizers corresponding to that tuple is not the identity operator in the 7-qubit Pauli group.
    # repeat is a keyword for the product function from itertools that tells the function to compute the Cartesian product of [0,1] with itself repeat = len(Stabilizers) = 6 times.
    for exponents in product([0, 1], repeat=len(Stabilizers)):
        if exponents != (0, 0, 0, 0, 0, 0):
            assert stabilizer_product(exponents) != identity


# this checks to make sure that no product of the stabilizer generators gives -I. This ensures that the subgroup generated by the elements in Stabilizers satisfies one of the
# few main conditions defining a stabilizer for a stabilizer code.
def test_minus_identity_not_in_stabilizer():
    minus_identity = Pauli("-IIIIIII")

    for exponents in product([0, 1], repeat=len(Stabilizers)):
        if exponents != (0, 0, 0, 0, 0, 0):
            assert stabilizer_product(exponents) != minus_identity
